---
- name: Installation node exporter on hosts
  hosts: all
  tasks: 
    - name: Copy node_exporter binary on remote host
      copy:
        src: files/node_exporter
        dest: /usr/local/bin/node_exporter
        owner: root
        group: root
        mode: '751'
    - name: Copy node_exporter.service on remote host
      copy:
        src: files/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode:  '644'
    - name: Start and enable node_exporter service
      systemd:
        name: node_exporter.service
        daemon_reload: yes
        force: yes
        enabled: yes
        state: started 
