---
# tasks file for install-node-exporter
- name: Ubuntu
  include_tasks: ubuntu.yml
  when: 
    - (ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version == "20.04")
- name: Fedora
  include_tasks: fedora.yml
  when: 
    - (ansible_distribution|lower == "fedora" and ansible_distribution_major_version == "32")
- name: Centos 
  include_tasks: centos.yml
  when: 
    - (ansible_distribution|lower == "centos" and ansible_distribution_major_version == "7")
