---
- name: execute yum update
  yum:
    update_cache: '{{ packages_update }}'

- name: Upgrade all packages, excluding kernel & foo related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*,foo*
  when: packages_upgrade

- name: Install packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages_list }}"


- name: Remove dependencies that are no longer required
  yum:
    autoremove: "{{ packages_autoremove }}"